export const RULE_ACTIONS = {
  GET_ALL_RULES: "GET_ALL_RULES",
  ADD_RULE: "ADD_RULE",
  UPDATE_RULE: "UPDATE_RULE",
  DELETE_RULE: "DELETE_RULE",
  GET_RULE: "GET_RULE",
  SET_MESSAGE: "SET_MESSAGE"
};
