export const TEAM_ACTIONS = {
  GET_TEAM_LEADERBOARD: "GET_TEAM_LEADERBOARD",
  GET_MEMBER_LEADERBOARD: "GET_MEMBER_LEADERBOARD",
  ADD_RULE: "ADD_RULE",
  SET_TEAM_DETAILS: "SET_TEAM_DETAILS",
  SET_MESSAGE: "SET_MESSAGE"
};
